{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jacamo",
    "module": "nagent-adapt",
    "version": "1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "nagent-adapt-1.1.jar",
          "url": "nagent-adapt-1.1.jar",
          "size": 67988,
          "sha512": "0456cf931f9b16d129f785e9d96dba8200aa0caf3c8c11d7fb7743c722ba3a0a43b490a98081e163d3e37cd40c831d2e61a726f8426a33062fb0a9c12cde9bfd",
          "sha256": "e6060821ba1f3532c632e3f457fc9c168205b3468b22d03923f3c401701de062",
          "sha1": "ab067c079edbfe02ebd2ac719bdd7c0d6bb2cc75",
          "md5": "61678ae5813b02943304f3d8f18bb1b0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jacamo",
          "module": "jacamo",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jacamo",
          "module": "npl",
          "version": {
            "requires": "0.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "nagent-adapt-1.1.jar",
          "url": "nagent-adapt-1.1.jar",
          "size": 67988,
          "sha512": "0456cf931f9b16d129f785e9d96dba8200aa0caf3c8c11d7fb7743c722ba3a0a43b490a98081e163d3e37cd40c831d2e61a726f8426a33062fb0a9c12cde9bfd",
          "sha256": "e6060821ba1f3532c632e3f457fc9c168205b3468b22d03923f3c401701de062",
          "sha1": "ab067c079edbfe02ebd2ac719bdd7c0d6bb2cc75",
          "md5": "61678ae5813b02943304f3d8f18bb1b0"
        }
      ]
    }
  ]
}
