{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jacamo",
    "module": "nagent-adapt",
    "version": "1.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "nagent-adapt-1.3.1.jar",
          "url": "nagent-adapt-1.3.1.jar",
          "size": 78734,
          "sha512": "32af8b217a8fef2390b7a31c4e2208e50282c1b1a1913ea3c7475947a57afa51e107c9e094c70358147fa6daf44d0f6d2035e8dbdb585fb2ba999b340482d5c8",
          "sha256": "8a9004e8c3d33f73eefc1d9ef5fdc3dda924e6467eed6ea3eaa951ffc904d7b1",
          "sha1": "bfd1ca4fa22addc1b54dc2e84114bc042c4a4110",
          "md5": "e14287ea014f54101fb78eb33ad25e58"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jacamo",
          "module": "jacamo",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jacamo",
          "module": "npl",
          "version": {
            "requires": "0.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "nagent-adapt-1.3.1.jar",
          "url": "nagent-adapt-1.3.1.jar",
          "size": 78734,
          "sha512": "32af8b217a8fef2390b7a31c4e2208e50282c1b1a1913ea3c7475947a57afa51e107c9e094c70358147fa6daf44d0f6d2035e8dbdb585fb2ba999b340482d5c8",
          "sha256": "8a9004e8c3d33f73eefc1d9ef5fdc3dda924e6467eed6ea3eaa951ffc904d7b1",
          "sha1": "bfd1ca4fa22addc1b54dc2e84114bc042c4a4110",
          "md5": "e14287ea014f54101fb78eb33ad25e58"
        }
      ]
    }
  ]
}
