{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jacamo",
    "module": "nagent-adapt",
    "version": "1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "nagent-adapt-1.2.jar",
          "url": "nagent-adapt-1.2.jar",
          "size": 71774,
          "sha512": "8d27596c6a29594f7706fe95c57b920adf104806e85839e5651c36c20ca58bcebcc9e52f8cfe831d42f16514781af6de3db1b545ca75dd18bdc75379c428b74e",
          "sha256": "e63dae59d36657417bcf11b20229c9420bf4492945c17fe2464de468fbdaea46",
          "sha1": "9b717e98a909fedf6abcd8215f140def09ed5008",
          "md5": "f11f08480922f81dbb65df07bc1e32df"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jacamo",
          "module": "jacamo",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jacamo",
          "module": "npl",
          "version": {
            "requires": "0.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "nagent-adapt-1.2.jar",
          "url": "nagent-adapt-1.2.jar",
          "size": 71774,
          "sha512": "8d27596c6a29594f7706fe95c57b920adf104806e85839e5651c36c20ca58bcebcc9e52f8cfe831d42f16514781af6de3db1b545ca75dd18bdc75379c428b74e",
          "sha256": "e63dae59d36657417bcf11b20229c9420bf4492945c17fe2464de468fbdaea46",
          "sha1": "9b717e98a909fedf6abcd8215f140def09ed5008",
          "md5": "f11f08480922f81dbb65df07bc1e32df"
        }
      ]
    }
  ]
}
