{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jacamo",
    "module": "nagent-adapt",
    "version": "1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "nagent-adapt-1.2.jar",
          "url": "nagent-adapt-1.2.jar",
          "size": 71234,
          "sha512": "e56207d7a82f1357451108c066351649607490efe32152dfd49494f8863f48688075f68db69a6843f97a7b7808190806ae9ca22bf882c9f689cde68f1cee8ae3",
          "sha256": "886aed60e6dcc5ec4d7a7977f33c70bdd364ff4658ac664b68f192a5bd712e18",
          "sha1": "2d47d49db66197a53e2697a99dafd390e4b67247",
          "md5": "132d3ebb9e98dbeab14fc4cad969d047"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jacamo",
          "module": "jacamo",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jacamo",
          "module": "npl",
          "version": {
            "requires": "0.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "nagent-adapt-1.2.jar",
          "url": "nagent-adapt-1.2.jar",
          "size": 71234,
          "sha512": "e56207d7a82f1357451108c066351649607490efe32152dfd49494f8863f48688075f68db69a6843f97a7b7808190806ae9ca22bf882c9f689cde68f1cee8ae3",
          "sha256": "886aed60e6dcc5ec4d7a7977f33c70bdd364ff4658ac664b68f192a5bd712e18",
          "sha1": "2d47d49db66197a53e2697a99dafd390e4b67247",
          "md5": "132d3ebb9e98dbeab14fc4cad969d047"
        }
      ]
    }
  ]
}
