{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jacamo",
    "module": "nagent-adapt",
    "version": "1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "nagent-adapt-1.2.jar",
          "url": "nagent-adapt-1.2.jar",
          "size": 72096,
          "sha512": "98e27869725a0a6ef4f58e00ad5504433b2b85e99232395e5dc7963ebebb8f0030dc134d70c29ace4bfe439350ce75b63732eb69360942db53a46c3d5e0333e3",
          "sha256": "cfebd363104b78b51ea2c32ce7aba7983bb10e17eaf53c0d9d1e3ff49b8a84cb",
          "sha1": "b99410b738cfda54cbf15c3ff7a734eb2e18bcaa",
          "md5": "e4d73b2a1e698c731697170ebe606c7e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jacamo",
          "module": "jacamo",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jacamo",
          "module": "npl",
          "version": {
            "requires": "0.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "nagent-adapt-1.2.jar",
          "url": "nagent-adapt-1.2.jar",
          "size": 72096,
          "sha512": "98e27869725a0a6ef4f58e00ad5504433b2b85e99232395e5dc7963ebebb8f0030dc134d70c29ace4bfe439350ce75b63732eb69360942db53a46c3d5e0333e3",
          "sha256": "cfebd363104b78b51ea2c32ce7aba7983bb10e17eaf53c0d9d1e3ff49b8a84cb",
          "sha1": "b99410b738cfda54cbf15c3ff7a734eb2e18bcaa",
          "md5": "e4d73b2a1e698c731697170ebe606c7e"
        }
      ]
    }
  ]
}
