{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jacamo",
    "module": "logging-component",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "logging-component-1.0.jar",
          "url": "logging-component-1.0.jar",
          "size": 107616,
          "sha512": "8a215a210a6cc7869ec196024cc1a93e0da73ae3be3724ff76b22681c202c01ccd105f0311698b560f197d86e3de4f9aac8c6f8867a98d0f5d911e8f39277917",
          "sha256": "7934eaada647a31a52e7db64555d3626a5f9d81760fde31226f2f19e9a03f50c",
          "sha1": "64c3876fc4510c0bc0e1da15798ac60d7bd2b150",
          "md5": "4b2d68b59a6431cb7fc1696defb5bcd3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.8"
          }
        },
        {
          "group": "io.github.jason-lang",
          "module": "jason-interpreter",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "org.jacamo",
          "module": "jacamo",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jacamo",
          "module": "npl",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "org.jacamo",
          "module": "nagent-adapt",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "logging-component-1.0.jar",
          "url": "logging-component-1.0.jar",
          "size": 107616,
          "sha512": "8a215a210a6cc7869ec196024cc1a93e0da73ae3be3724ff76b22681c202c01ccd105f0311698b560f197d86e3de4f9aac8c6f8867a98d0f5d911e8f39277917",
          "sha256": "7934eaada647a31a52e7db64555d3626a5f9d81760fde31226f2f19e9a03f50c",
          "sha1": "64c3876fc4510c0bc0e1da15798ac60d7bd2b150",
          "md5": "4b2d68b59a6431cb7fc1696defb5bcd3"
        }
      ]
    }
  ]
}
