{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jacamo",
    "module": "nagent-adapt",
    "version": "1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "nagent-adapt-1.3.jar",
          "url": "nagent-adapt-1.3.jar",
          "size": 78484,
          "sha512": "020179a549c5b91b0154f01bb4a530c754a133e7b20a0adf67f531f8c86878a8521008bc40ea524a1d4b15e6519e594227cca4f86120f419fb665a87033805c9",
          "sha256": "0dd90a07b2dac6f35b9c1dfb3002a248a00a4c15ad58fcea2453780e03872b11",
          "sha1": "dc44e0e8d954407716e6035ec56425523bb580e3",
          "md5": "923374b1f7bab1025d2121e9770c8d0c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jacamo",
          "module": "jacamo",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jacamo",
          "module": "npl",
          "version": {
            "requires": "0.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "nagent-adapt-1.3.jar",
          "url": "nagent-adapt-1.3.jar",
          "size": 78484,
          "sha512": "020179a549c5b91b0154f01bb4a530c754a133e7b20a0adf67f531f8c86878a8521008bc40ea524a1d4b15e6519e594227cca4f86120f419fb665a87033805c9",
          "sha256": "0dd90a07b2dac6f35b9c1dfb3002a248a00a4c15ad58fcea2453780e03872b11",
          "sha1": "dc44e0e8d954407716e6035ec56425523bb580e3",
          "md5": "923374b1f7bab1025d2121e9770c8d0c"
        }
      ]
    }
  ]
}
